import React from "react";
import { motion } from "framer-motion";
import {
  Grid,
  Box,
  GridItem,
  Heading,
  Image,
  SimpleGrid,
  Text,
} from "@chakra-ui/react";

const Skills = () => {
  return (
    <div id="skills">
      <Heading textAlign="center" mt="85" mb="25" color="#48BB78">
        Skills
      </Heading>
      <SimpleGrid
        minChildWidth="140px"
        w="80%"
        m="auto"
        gap={6}
        mb="50"
        className="skillsDiv"
      >
        <Box
          colSpan={1}
          w="100%"
          m="auto"
          rounded="md"
          alignItems="center"
          justifyContent="center"
          textAlign="center"
          className="skillsLogo"
        >
          <Image
            src="https://sandeshjadhav5.github.io/static/media/html-5.e7638e3676622c76a46ece6c46136fd4.svg"
            m="auto"
            w="100px"
            h="50px"
          />
          <Text mt={5} fontWeight={600}>
            HTML
          </Text>
        </Box>
        <Box
          colSpan={1}
          w="100%"
          m="auto"
          rounded="md"
          alignItems="center"
          justifyContent="center"
          textAlign="center"
          className="skillsLogo"
        >
          <Image
            src="https://sandeshjadhav5.github.io/static/media/css-3.e7a9de36d9335d92932e93eb3b32deb9.svg"
            m="auto"
            w="72px"
            h="50px"
          />
          <Text mt={5} fontWeight={600}>
            CSS
          </Text>
        </Box>
        <Box
          colSpan={1}
          w="100%"
          m="auto"
          rounded="md"
          alignItems="center"
          justifyContent="center"
          textAlign="center"
          className="skillsLogo"
        >
          <Image
            src="https://sandeshjadhav5.github.io/static/media/javascript.fd46ca41839433d73577989d86eb2fe2.svg"
            m="auto"
            w="72px"
            h="50px"
          />
          <Text mt={5} fontWeight={600}>
            JavaScript
          </Text>
        </Box>
        <Box
          colSpan={1}
          w="100%"
          m="auto"
          rounded="md"
          alignItems="center"
          justifyContent="center"
          textAlign="center"
          className="skillsLogo"
        >
          <Image
            src="https://sandeshjadhav5.github.io/static/media/react.e27571eaed899c642345e71163624ef9.svg"
            m="auto"
            w="82px"
            h="50px"
          />
          <Text mt={5} fontWeight={600}>
            React
          </Text>
        </Box>
        <Box
          colSpan={1}
          w="100%"
          m="auto"
          rounded="md"
          alignItems="center"
          justifyContent="center"
          textAlign="center"
          className="skillsLogo"
        >
          <Image
            src="https://sandeshjadhav5.github.io/static/media/redux.a95675408ae17c456965e2f09376c31a.svg"
            m="auto"
            w="82px"
            h="50px"
          />
          <Text mt={5} fontWeight={600}>
            Redux
          </Text>
        </Box>
        <Box
          colSpan={1}
          w="100%"
          m="auto"
          rounded="md"
          alignItems="center"
          justifyContent="center"
          textAlign="center"
          className="skillsLogo"
        >
          <Image
            src="https://sandeshjadhav5.github.io/static/media/mongodb.153b7b440efa05666029a47da0d0baa0.svg"
            m="auto"
            w="80px"
            h="50px"
          />
          <Text mt={5} fontWeight={600}>
            MongoDB
          </Text>
        </Box>
        <Box
          colSpan={1}
          w="100%"
          m="auto"
          rounded="md"
          alignItems="center"
          justifyContent="center"
          textAlign="center"
          className="skillsLogo"
        >
          <Image
            src="https://raw.githubusercontent.com/tomchen/stack-icons/634d5c036a2a7ca0115c94ab2ce86c7e79e01e13/logos/express.svg"
            m="auto"
            w="80px"
            h="50px"
          />

          <Text mt={5} fontWeight={600}>
            Express
          </Text>
        </Box>
        <Box
          colSpan={1}
          w="100%"
          m="auto"
          rounded="md"
          alignItems="center"
          justifyContent="center"
          textAlign="center"
          className="skillsLogo"
        >
          <Image
            src="https://sandeshjadhav5.github.io/static/media/node_js.27d0e4077d4d9a98207386bb92245b6a.svg"
            m="auto"
            w="80px"
            h="50px"
          />
          <Text mt={5} fontWeight={600}>
            Node JS
          </Text>
        </Box>
        <Box
          colSpan={1}
          w="100%"
          m="auto"
          rounded="md"
          alignItems="center"
          justifyContent="center"
          textAlign="center"
          className="skillsLogo"
        >
          <Image
            src="https://git-scm.com/images/logos/downloads/Git-Icon-1788C.png"
            m="auto"
            w="80px"
            h="50px"
          />
          <Text mt={5} fontWeight={600}>
            Git
          </Text>
        </Box>
        <Box
          colSpan={1}
          w="100%"
          m="auto"
          rounded="md"
          alignItems="center"
          justifyContent="center"
          textAlign="center"
          className="skillsLogo"
        >
          <Image
            src="https://cdn-icons-png.flaticon.com/512/5968/5968381.png"
            m="auto"
            w="60px"
            h="50px"
          />

          <Text mt={5} fontWeight={600}>
            TypeScript
          </Text>
        </Box>
        <Box
          colSpan={1}
          w="100%"
          m="auto"
          rounded="md"
          alignItems="center"
          justifyContent="center"
          textAlign="center"
          className="skillsLogo"
        >
          <Image
            src="https://sandeshjadhav5.github.io/static/media/cypress.071c7e709ef3dbea48931ab4d60f4e3b.svg"
            m="auto"
            w="80px"
            h="50px"
          />
          <Text mt={5} fontWeight={600}>
            Cypress
          </Text>
        </Box>
        <Box
          w="100%"
          m="auto"
          rounded="md"
          alignItems="center"
          justifyContent="center"
          textAlign="center"
          className="skillsLogo"
        >
          <Image
            src="https://avatars.githubusercontent.com/u/54212428?s=280&v=4"
            m="auto"
            w="60px"
            h="50px"
          />
          <Text mt={5} fontWeight={600}>
            Chakra UI
          </Text>
        </Box>
        <Box
          w="100%"
          m="auto"
          rounded="md"
          alignItems="center"
          justifyContent="center"
          textAlign="center"
          className="skillsLogo"
        >
          <Image
            src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Bootstrap_logo.svg/512px-Bootstrap_logo.svg.png?20210507000024"
            m="auto"
            w="60px"
            h="50px"
          />
          <Text mt={5} fontWeight={600}>
            BootStrap
          </Text>
        </Box>
        <Box
          w="100%"
          m="auto"
          rounded="md"
          alignItems="center"
          justifyContent="center"
          textAlign="center"
          className="skillsLogo"
        >
          <Image
            src="https://static-00.iconduck.com/assets.00/npm-icon-512x512-qtfdrf37.png"
            m="auto"
            w="60px"
            h="50px"
          />
          <Text mt={5} fontWeight={600}>
            npm
          </Text>
        </Box>
      </SimpleGrid>
      {/* <Image src={html5} /> */}
    </div>
  );
};

export default Skills;
